server:
  resource:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 512Mi

prometheus-pushgateway:
  enabled: false

alertmanager:
  enabled: false

prometheus-node-exporter:
  enabled: false

kube-state-metrics:
  resources:
    requests:
      cpu: 10m
      memory: 32Mi
    limits:
      cpu: 100m
      memory: 64Mi
